from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
import reversion
import overdiff
from datetime import datetime, timedelta
from reversion.models import Version

import pdb
import markdown

# from http://dwiel.net/blog/python-parsing-the-output-of-datetime-isoformat/
def _parse_iso_datetime(s) :
    # parse a datetime generated by datetime.isoformat()
    try :
        return datetime.strptime(s, "%Y-%m-%dT%H:%M:%S")
    except ValueError :
        return datetime.strptime(s, "%Y-%m-%dT%H:%M:%S.%f")

def serve_highlighted_text(request, slug, model, field_to_diff, sessionvar, template='lhighlight/highlight.html'):
    obj = get_object_or_404(model, slug=slug)

    if not hasattr(obj, field_to_diff):
        raise Exception("the selected object does not have a %s field" % field_to_diff)

    fromdate = None
    fromdate = request.GET.get('since', None)
    fromdate = request.session.get(sessionvar, None) if not fromdate else fromdate
    fromdate = unicode(datetime.now().isoformat()) if not fromdate else fromdate
    fromdate = _parse_iso_datetime(fromdate) if fromdate else None


    todate = datetime.now()

    current = reversion.get_for_date(obj, todate).field_dict
    previous = reversion.get_for_date(obj, fromdate).field_dict

    current_field = current[field_to_diff].replace('\r','')
    previous_field = previous[field_to_diff].replace('\r','')

    current_field_pars = current_field.split('\n\n')
    previous_field_pars = previous_field.split('\n\n')

    field_diff_data = list(overdiff.overdiff(previous_field_pars, current_field_pars))
    field_diffs = []

    for i in xrange(0,len(field_diff_data)):
        field_diffs.append(overdiff.selection_to_s(current_field_pars[i], field_diff_data[i]))
    field_diff = '\n\n'.join(field_diffs)

    dates = []
    tmpdate = obj.published
    tmpversion = None
    while tmpdate < datetime.now():
        tmpversion2 = None
        try:
            tmpversion2 = reversion.get_for_date(obj, tmpdate)
        except Version.DoesNotExist:
            pass
        changed = (tmpversion != tmpversion2)
        dates.append((tmpversion2.revision.date_created if tmpversion2 else tmpdate, changed,))
        tmpdate += timedelta(days=1)
        tmpversion = tmpversion2

    return render_to_response(template, {
        'current': current,
        'previous': previous,
        'field_diff': field_diff,
        'fromdate': fromdate,
        'todate': todate,
        'versiondates': dates,
        }, context_instance=RequestContext(request))

